# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wDMNjHVQichQpwZu1I8yO2ozMchvsLA
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
 import numpy as np
 import matplotlib.pyplot as plt
 from random import seed 
 from random import randint
 import time

seed(time.time())


Xiter = [0]
itera = 0
fc = 0
Ynumone = [1]
array = np.zeros(1000)
array[randint(100, 999)] = 1


while(True):
  itera = itera + 1

  for _ in range(1000):
    if(array[_] == 1):
      j = randint(0, 1)
      array[(_ + j - (1-j) + 1000)%1000] = 1
  
  ind1 = randint(0, 999)
  ind2 = randint(0, 999)
  temp = array[ind1]
  array[ind1] = array[ind2]
  array[ind2] = temp

    
  count = 0
  for _ in range(1000):
    count += array[_]
  
  Xiter.append(itera)
  Ynumone.append(count)

  if count == 1000:
    fc = itera
    break

print("It takes ", itera, " iterations to set all indices")
plt.plot(Xiter, Ynumone)
plt.xlabel("Iteration count")
plt.ylabel("nmber of set indices")
plt.savefig("Tanay-iter5.png")

!git init
!git config-global.user.email "greettanay@gmail.com"
!git config-global.user.name "tantheta01"

!git config --global user.email "greettanay@gmail.com"
!git config --global user.name "tantheta01"

!git add -A

!git commit -m "First commit"

!git remote add origin git@github.com:tantheta01/Intelligent-Agents-SoC.git

!git push -u origin master

!git remote rm origin

